// src/pages/Login.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import api from '../services/api';


export default function Login() {
    const [email, setEmail] = useState('');
    const [senha, setSenha] = useState('');
    const navigate = useNavigate();

    const login = async (e) => {
        e.preventDefault();
        try {
            const res = await api.post('/auth/login', { email, senha });
            localStorage.setItem('token', res.data.token);
            navigate('/');
        } catch (err) {
            alert('Login falhou!');
        }
    };

    return (
        <form className="container" onSubmit={login}>
            <h2>Login</h2>
            <input placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} />
            <input placeholder="Senha" type="password" value={senha} onChange={e => setSenha(e.target.value)} />
            <button type="submit">Entrar</button>
            <p>Não tem uma conta? Acesse <Link to="/register">Cadastro</Link></p>
        </form>
    );
}

// src/views/Login.vue
<template>
  <h2>Login</h2>
  <form @submit.prevent="login">
    <input v-model="email" placeholder="Email" />
    <input v-model="senha" type="password" placeholder="Senha" />
    <button type="submit">Entrar</button>
  </form>
  <p v-if="erro">{{ erro }}</p>
</template>

<script>
import api from '../services/api';

export default {
  data() {
    return { email: '', senha: '', erro: '' };
  },
  methods: {
    async login() {
      try {
        const res = await api.post('/auth/login', { email: this.email, senha: this.senha });
        localStorage.setItem('token', res.data.token);
        localStorage.setItem('refreshToken', res.data.refreshToken);
        this.$router.push('/');
      } catch (e) {
        this.erro = 'Credenciais inválidas';
      }
    }
  }
};
</script>
