// src/App.jsx
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Login from './pages/Login';
import Register from './pages/Register';
import Home from './pages/Home';
import PrivateRoute from './components/PrivateRoute';

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/login" element={<Login />} />
        <Route path="/register" element={<Register />} />
        <Route element={<PrivateRoute />}>
          <Route path="/home" element={<Home />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}

// src/App.vue
<template>
  <NavBar v-if="mostrarNavBar" />
  <router-view />
</template>

<script setup>
import { useRoute } from 'vue-router';
import { computed } from 'vue';
import NavBar from './components/NavBar.vue';

const route = useRoute();
const mostrarNavBar = computed(() => !['/login', '/register'].includes(route.path));
</script>
